// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class DefaultSuiteTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void navegacion() {
    driver.Navigate().GoToUrl("https://localhost:5001/");
    driver.Manage().Window.Size = new System.Drawing.Size(1532, 813);
    driver.FindElement(By.LinkText("Privacy")).Click();
    driver.FindElement(By.LinkText("Home")).Click();
    driver.FindElement(By.LinkText("Login")).Click();
    driver.FindElement(By.Id("Input_Email")).Click();
    driver.FindElement(By.Id("Input_Email")).SendKeys("kk@kk");
    driver.FindElement(By.Id("Input_Password")).SendKeys("P@$$w0rd");
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.LinkText("Productos")).Click();
    driver.FindElement(By.LinkText("Edit")).Click();
    Assert.That(driver.FindElement(By.CssSelector("h1:nth-child(2)")).Text, Is.EqualTo("Create"));
    driver.FindElement(By.CssSelector(".btn-link")).Click();
  }
}
